# Generated by Django 3.0.6 on 2020-05-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('kkal', models.IntegerField()),
                ('price', models.FloatField(max_length=60)),
            ],
            options={
                'db_table': 'Dishes',
            },
        ),
    ]
