# Generated by Django 3.0.6 on 2020-05-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupcakes', '0003_auto_20200516_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='id',
            new_name='code_call',
        ),
    ]
