# Generated by Django 3.0.6 on 2020-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupcakes', '0005_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(default='weight', max_length=60),
        ),
    ]
