# Generated by Django 3.0.6 on 2020-05-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupcakes', '0006_dish_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='Dish',
        ),
    ]
